# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'searchbarTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  # Pods for searchbarTest

  target 'searchbarTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'searchbarTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
