# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftScanTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  # Pods for RxSwiftScanTest

  target 'RxSwiftScanTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftScanTestUITests' do
    # Pods for testing
  end

end
