# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'transitionTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  # Pods for transitionTest

  target 'transitionTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'transitionTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
